indicative_templates = [
    "If the sun rises early, we will have more daylight.",
    "She will forgive you if you apologize sincerely.",
    "Unless the roads are closed, they'll reach on time.",
    "You may attend the meeting provided that you register beforehand.",
    "If he finishes his chores, he can watch TV.",
    "If you leave now, you might catch the bus.",
    "The cake will burn unless you take it out soon.",
    "Provided that the power stays on, the concert will continue.",
    "If they don't hurry, they'll miss the opening act.",
    "On condition that he behaves, he can stay up late.",
    "You can go to the park if your homework is done.",
    "If the weather improves, we'll have the picnic outside.",
    "The room feels colder if the window is left open.",
    "If water reaches 100°C, it boils.",
    "Unless I hear otherwise, I'll assume everything's fine.",
    "Provided that everyone agrees, we'll sign the contract.",
    "You will succeed if you remain focused.",
    "If I get the job, we'll celebrate tonight.",
    "On condition that you wear a helmet, you can ride the bike.",
    "We'll meet at noon unless plans change.",
    "If she sings, the crowd will cheer.",
    "You can take the car if you return by 10.",
    "Provided that tickets are available, we'll attend the show.",
    "If the alarm rings, evacuate the building.",
    "The team wins if they score one more goal.",
    "Unless we act now, the opportunity will be lost.",
    "If the printer works, we'll hand out the flyers.",
    "You may borrow my notes if you return them tomorrow.",
    "The dog barks if strangers approach the house.",
    "We'll head to the beach if it stays sunny.",
    "You'll miss your chance unless you apply soon.",
    "If I call, answer right away.",
    "On condition that he pays upfront, the deal is his.",
    "She'll bake a cake if there's enough flour.",
    "Unless the rules change, we can't proceed.",
    "You can play outside if you wear sunscreen.",
    "If he trains hard, he might win the race.",
    "Provided that traffic is light, we'll be on time.",
    "If the lights are off, they've likely left.",
    "You will improve if you practice regularly.",
    "If the baby sleeps, we'll watch a movie.",
    "She'll travel to Rome if she gets time off work.",
    "On condition that he passes the test, he'll graduate.",
    "If the guests arrive early, serve the drinks.",
    "Unless she objects, we'll start the meeting.",
    "You may use the lab if you follow the safety rules.",
    "Provided that I feel well, I'll join the hike.",
    "If he skips lunch, he gets cranky.",
    "We will go dancing if the club is open.",
    "The flowers bloom if spring arrives early.",
    "If it gets cold, bring a jacket.",
    "On condition that you behave, you may attend.",
    "If she studies medicine, she'll help many people.",
    "You'll feel better if you rest for a while.",
    "Unless it's urgent, don't call during the movie.",
    "If the signal is strong, the video will stream smoothly.",
    "Provided that the chef is available, we'll book the event.",
    "She can enter if her name is on the list.",
    "If the children nap, we can clean the house.",
    "On condition that he signs today, we'll proceed.",
    "You will enjoy the film if you like action movies.",
    "If the ice melts, the level will rise.",
    "Unless I forget, I'll email you the details.",
    "Provided that the gate is unlocked, we'll walk through.",
    "If the instructions are clear, they'll finish fast.",
    "You can drive if your license is valid.",
    "If there's time, we'll visit the museum.",
    "She can join us if she finishes work early.",
    "Unless the forecast is wrong, it will rain tomorrow.",
    "If we finish in time, we'll catch dinner together.",
    "On condition that it's safe, they'll resume hiking.",
    "You'll get a bonus if you reach your targets.",
    "Provided that it's affordable, we'll buy it.",
    "If the train arrives on schedule, we're good.",
    "Unless I'm mistaken, this is the right path.",
    "You may ask questions if you raise your hand.",
    "If the document is signed, the process begins.",
    "She can start her shift if the previous one ends.",
    "On condition that she agrees, the proposal moves forward.",
    "If the temperature drops, cover the plants.",
    "Provided that all items are packed, we'll leave soon.",
    "If the software updates, the bug should disappear.",
    "Unless we plan ahead, we'll run out of time.",
    "You can attend the wedding if you RSVP.",
    "If his schedule allows, he'll make a speech.",
    "On condition that it's clean, you may use the lab.",
    "If the funding is approved, construction starts Monday.",
    "Provided that we rehearse, the show will go well.",
    "You may leave if the test is complete.",
    "Unless there's a delay, we land at 8.",
    "If the speaker arrives, begin the session.",
    "She'll help if she understands the task.",
    "If they agree, the plan proceeds as scheduled.",
    "On condition that the lights work, we'll record tonight.",
    "If you follow directions, it'll be easy.",
    "Provided that I get paid, I'll do the job.",
    "Unless the manager objects, we'll order lunch.",
    "You can run the code if the compiler works.",
    "If she calls back, give her the update.",
    "If the lock is broken, replace it immediately.",
    "On condition that all seats are full, close the doors.",
    "Provided that the mic works, begin the speech.",
    "If the laptop is charged, we can start the presentation.",
    "You'll get a reward if you find the missing keys.",
    "If the cat is hungry, it will meow loudly.",
    "Unless the documents are signed, we cannot proceed.",
    "If the oven preheats in time, dinner will be ready by six.",
    "Provided that you attend all sessions, you'll receive a certificate.",
    "The machine starts if you press the green button.",
    "On condition that the weather holds, we'll camp overnight.",
    "If the baby wakes up, please call me.",
    "He can join the tournament if he qualifies in preliminaries.",
    "If the exam ends early, we'll go for ice cream.",
    "You'll understand it better if you reread the chapter.",
    "Provided that she brings her notes, we can study together.",
    "If the team wins this round, they enter the finals.",
    "Unless the schedule changes, the bus departs at 4.",
    "He'll accept the offer if the terms are reasonable.",
    "If she replies soon, we can confirm the date.",
    "On condition that it's safe, we'll open the gates.",
    "If the email doesn't bounce, assume it was received.",
    "You'll unlock the bonus level if you beat the boss.",
    "Unless we act fast, the deal might expire.",
    "If the coffee is too hot, let it cool a minute.",
    "Provided that the lights are on, someone's inside.",
    "If I see her at the store, I'll say hello.",
    "On condition that there's time, we'll play another round.",
    "If the dog barks at night, check the backyard.",
    "He will start painting if the supplies arrive.",
    "Unless the password is correct, access will be denied.",
    "If she wears the red dress, she'll turn heads.",
    "You'll lose signal if we go through the tunnel.",
    "Provided that we keep quiet, we might see the deer.",
    "If the delivery comes, sign for it.",
    "On condition that there's space, we'll bring another guest.",
    "If he walks to work, he arrives in a better mood.",
    "Unless the report is printed, we can't distribute it.",
    "If the water is clear, we'll swim.",
    "You'll enjoy the festival if you love music.",
    "Provided that the babysitter is free, we'll book the night out.",
    "If the bread rises properly, it'll be fluffy.",
    "She'll take the lead if her name is called.",
    "If the garbage is full, take it out.",
    "On condition that the books arrive, we'll start the unit.",
    "You can submit your project if the portal is open.",
    "Unless I receive an update, I'll assume the meeting's on.",
    "If the new intern starts Monday, show him around.",
    "You'll gain access if you complete the tutorial.",
    "Provided that everyone agrees, we'll finalize the logo.",
    "If she passes the exam, she'll qualify for the scholarship.",
    "If it's sunny, we'll go to the botanical gardens.",
    "He'll join the band if they offer him the drummer slot.",
    "If the bill is paid, no late fee applies.",
    "You can book the room if it's not taken.",
    "Unless there's interference, the drone should remain stable.",
    "If I return in time, we'll eat together.",
    "Provided that there's room, you can ride with us.",
    "If the application is complete, submit it today.",
    "She will volunteer if she has no other plans.",
    "Unless the door is locked, feel free to enter.",
    "If the letter arrives tomorrow, we can reply immediately.",
    "On condition that he agrees, we'll make the announcement.",
    "You'll feel warmer if you wear two layers.",
    "Provided that the code compiles, the test should pass.",
    "If the sun sets soon, we'll light the lanterns.",
    "Unless the music is too loud, leave it playing.",
    "If I'm free on Saturday, I'll join the hike.",
    "He'll take the lead if no one else volunteers.",
    "On condition that the glass is clean, use it for wine.",
    "If the ice cream melts, put it back in the freezer.",
    "You'll receive a response if you submit the form.",
    "Unless they extend the deadline, it's due Friday.",
    "If the package is too large, it won't fit the locker.",
    "Provided that we finish by six, we can catch the movie.",
    "If the ink runs out, replace the cartridge.",
    "She'll be on time if she leaves by nine.",
    "If the fire alarm sounds, evacuate the building.",
    "On condition that the paint dries, we'll hang the art.",
    "If they leave early, they'll beat the traffic.",
    "Unless you're certain, don't confirm the date yet.",
    "You can adopt a pet if your landlord allows it.",
    "If the park is crowded, we'll go elsewhere.",
    "Provided that the mic is working, begin the speech.",
    "If you study tonight, you'll feel more prepared.",
    "She'll return the book if she finishes reading it.",
    "Unless I'm mistaken, this is her handwriting.",
    "If the roof holds, the interior will stay dry.",
    "On condition that we bring snacks, we can stay late.",
    "If the show is sold out, we'll pick another.",
    "You'll miss your window if you wait too long.",
    "Provided that it doesn't rain, the match will go on.",
    "If we hit traffic, take the alternate route.",
    "Unless the alarm is set, the system won't arm.",
    "If you flip the switch, the fan turns on.",
    "She will rest if the pain persists.",
    "If the internet is slow, reset the router.",
    "On condition that the floor is dry, we'll dance here.",
    "Provided that the stove is hot, begin cooking.",
    "If the toy breaks, return it to the store.",
    "On condition that the tent holds, we'll stay the night.",
    "If the conference runs over time, we'll need to reschedule the last speaker.",
    "You should bring a jacket if you're heading out after sunset.",
    "If the user logs in successfully, the dashboard will be displayed.",
    "We’ll consider your proposal if you submit it before Friday.",
    "If the power returns soon, we can resume the operation.",
    "You'll miss the introduction if you don’t leave now.",
    "If the instructions are unclear, the team may misinterpret the process.",
    "Should she arrive early, she’ll help set up the room.",
    "If the temperature keeps rising, the ice caps will continue melting.",
    "The project will proceed on time if all permits are secured.",
    "If you check the logs, you might find the source of the error.",
    "If they agree to the terms, we’ll finalize the contract.",
    "You can take the second left if the first road is closed.",
    "If the printer jams again, call the technician immediately.",
    "The door opens automatically if the card is scanned correctly.",
    "If the sun is too strong, apply extra sunscreen.",
    "We will postpone the picnic if it continues to drizzle.",
    "If she approves the draft, we can move to the next phase.",
    "If the alarm doesn’t stop, reset the system manually.",
    "You may enter the restricted area if you have clearance.",
    "If the book is overdue, a late fee will apply.",
    "Should he contact you first, let me know immediately.",
    "If the application crashes, restart your device.",
    "The payment will go through if your card is active.",
    "If the results are inconclusive, we’ll conduct a follow-up test.",
    "She’ll choose the red dress if it’s still available.",
    "If you boil the mixture too long, it will caramelize.",
    "If the candidate performs well, they may get the position.",
    "The dog barks if someone rings the bell.",
    "If the message fails to send, try resending it.",
    "Employees may leave early if the work is finished.",
    "If the satellite stays in orbit, we’ll get better coverage.",
    "Unless you want trouble, follow the posted rules.",
    "If the goods arrive today, we’ll ship them by morning.",
    "We’ll need more chairs if attendance exceeds expectations.",
    "If you hear back from them, send me an update.",
    "If the train is delayed again, we’ll request compensation.",
    "If he enters the room quietly, they won’t notice.",
    "If this key fits, the mystery will finally be solved.",
    "Call the vet if the swelling doesn’t go down.",
    "The event continues if the weather cooperates.",
    "If you clean the sensor, the reading should normalize.",
    "You'll be admitted if you bring the required documentation.",
    "If the deadline changes, please notify the team.",
    "If her phone battery dies, she won’t be reachable.",
    "Restart the router if the connection drops again.",
    "If the fire spreads, evacuate the building immediately.",
    "If the car breaks down, call roadside assistance.",
    "We can hike to the top if daylight permits.",
    "If you finish the puzzle, you can start a new one.",
    "Place the dough in the oven if it’s risen enough.",
    "If the tide is high, we’ll postpone the boat ride.",
    "You'll feel more relaxed if you meditate each morning.",
    "If no one volunteers, the task will be reassigned.",
    "If the button doesn’t respond, try pressing it harder.",
    "If your passport expires soon, you’ll need to renew it.",
    "If the child sleeps now, he’ll wake up cheerful.",
    "If the air conditioner malfunctions, report it to the front desk.",
    "If the proposal is accepted, funding will be released.",
    "You can go out if your chores are complete.",
    "If we move quickly, we can beat the traffic.",
    "The ceremony will begin if the guests are all seated.",
    "If there’s noise in the background, mute your mic.",
    "If the analysis is correct, our hypothesis is supported.",
    "The software will launch if all dependencies are loaded.",
    "You can have seconds if everyone else has eaten.",
    "If the doorbell rings, check the camera feed.",
    "If the plant receives enough sunlight, it will thrive.",
    "If we park closer, we’ll save time walking.",
    "The team may win if they coordinate better.",
    "If he speaks too fast, ask him to slow down.",
    "If the market improves, our investment will grow.",
    "She’ll be surprised if you remember her birthday.",
    "If this recipe turns out well, I’ll make it again.",
    "If the file doesn’t open, try a different app.",
    "If the offer is still valid, I might reconsider.",
    "If the timing is right, everything will align perfectly.",
    "If you overwater the cactus, it might rot.",
    "If the path splits, take the route on the left.",
    "If the students behave, we’ll play a review game.",
    "If I press this switch, the system resets.",
    "If we arrive before dark, we’ll catch the sunset.",
    "If the fridge is empty, we need to go shopping.",
    "If he speaks with the manager, we might get a refund.",
    "If the glue dries completely, it’ll hold for months.",
    "If the mic is too sensitive, adjust the gain.",
    "If you feel tired, take a short break.",
    "If the bills aren’t paid, service will be cut off.",
    "If the car is still under warranty, repairs are free.",
    "You can sit by the window if you’d like.",
    "If the crowd gets too loud, I’ll step outside.",
    "If you mark the calendar, you won’t forget.",
    "If your hands are full, use your elbow to push the door.",
    "If there’s food left, save it for tomorrow.",
    "If the sensor detects motion, the lights will come on.",
    "If the appointment runs late, reschedule the next client.",
    "If the movie is boring, we’ll leave early.",
    "If the meat isn’t thawed, we’ll make pasta instead.",
    "If the mood is tense, avoid controversial topics.",
    "If the translation is accurate, we’ll publish the article.",
    "If they miss this chance, they’ll regret it later.",
    "If the window won’t open, try the other side.",
    "If we take the shortcut, we might shave off 10 minutes.",
    "If the elevator is full, we’ll wait for the next one.",
    "If your phone rings, don’t answer during the meeting.",
    "If the soup is too salty, add a potato.",
    "If the ice machine is broken, call maintenance.",
    "If the page doesn’t load, refresh the browser.",
    "If you add too much salt, it’ll overpower the dish.",
    "If we leave now, we can catch the last train.",
    "If the candle flickers, there’s a draft somewhere.",
    "If your code compiles, you’re off to a good start.",
    "If the storm intensifies, we’ll shelter in place.",
    "If she signs the waiver, she can participate.",
    "If the system reboots, log back in with your credentials.",
    "If the gallery is closed, we’ll go to the café instead.",
    "If the jacket fits, you should buy it.",
    "If you explain your reasoning, others may agree.",
    "If the bridge is still under construction, take the detour.",
    "If the kids are asleep, let’s watch something loud.",
    "If your voice cracks, take a sip of water.",
    "If the results are positive, we’ll celebrate.",
    "If the puppy behaves, we’ll get it a new toy.",
    "If you miss the mark, try again tomorrow.",
    "If the data looks wrong, check the input fields.",
    "If it smells burnt, the toast is probably ruined.",
    "If she’s not home by midnight, text her.",
    "If the gate is locked, try the side entrance.",
    "If the washing machine leaks, turn off the valve.",
    "If we pass the intersection, turn around.",
    "If the restaurant’s too busy, try the diner next door.",
    "If the stars are visible, we’ll stargaze tonight.",
    "If the sound cuts out, wiggle the cable slightly.",
    "If he’s still upset, give him some space.",
    "If the check doesn’t clear, we’ll notify you.",
    "If your glasses fog up, try using anti-fog spray.",
    "If the line is too long, we’ll come back later.",
    "If I feel better tomorrow, I’ll join the team.",
    "If the schedule is packed, we’ll skip the tour.",
    "If the battery is low, charge it overnight.",
    "If it continues to rain, we’ll stay indoors.",
    "If your voice is hoarse, don’t push yourself.",
    "If the plan gets approved, we’ll begin immediately.",
    "If your computer slows down, clear some memory.",
    "If the lights flicker, there might be a short circuit.",
    "If the noise persists, call building management.",
    "If you’re feeling unsure, ask for clarification.",
    "If it starts snowing, bundle up before heading out.",
    "If they’re still waiting, bring them inside.",
    "If we’re still hungry, we can order dessert.",
    "If she’s available at noon, we’ll eat together.",
    "If there’s a delay, let the others know.",
    "If he logs in now, he’ll catch the meeting.",
    "If we act quickly, we can minimize the damage.",
    "If the path is slippery, walk slowly.",
    "If the stove is on, don’t leave the room unattended.",
    "If he keeps interrupting, mute his mic.",
    "If she doesn’t answer soon, try calling her mother.",
    "If this turns out to be a scam, report it.",
    "If the show is sold out, we’ll stream it instead.",
    "If you’ve already eaten, save me a plate.",
    "If he checks the settings, he might find the issue.",
    "If the door won’t budge, try using your shoulder.",
    "If the test is open-book, bring your materials.",
    "If she agrees to speak, we’ll put her first on the panel.",
    "If we catch the early train, we’ll get better seats.",
    "If no one objects, we’ll move forward as planned.",
    "If the audio echoes, reposition the microphone.",
    "If they choose the blue option, it’ll match the logo.",
    "If the clock is fast, we still have time.",
    "If the answer is wrong, explain why.",
    "If it’s not too much trouble, help me move this.",
    "If the delivery is early, we’ll unpack together.",
    "If the sauce curdles, whisk in some butter.",
    "If he acts up again, give him a warning.",
    "If the sensor trips again, disable it temporarily.",
    "If the printer runs out of ink, use the backup.",
    "If your foot hurts, take off your shoes.",
    "If the text is too small, zoom in.",
    "If no one laughs, it wasn’t funny.",
    "If she completes her hours, she’ll earn the credit.",
    "If we meet our quota, we’ll all get bonuses.",
    "If the light turns green, drive slowly across.",
    "If you finish early, use the extra time to review.",
    "If the toast burns, scrape it off.",
    "If the tea gets cold, reheat it in the microwave.",
    "If you lose your ticket, you can’t enter.",
    "If it snows overnight, expect delays.",
    "If the host arrives late, start without him.",
    "If he fixes the leak, we can turn the water back on.",
    "If it’s clean enough, leave it as is.",
    "If the remote stops working, replace the batteries.",
    "If the cushion is lumpy, fluff it up.",
    "If your browser crashes, reopen your tabs from history.",
    "If it’s sunny at noon, we’ll have lunch outside.",
    "If your ID is expired, bring another form of proof.",
    "If the student aces the final, she’ll pass the course.",
    "If the bread is fresh, don’t toast it.",
    "If this machine overheats, it will shut down automatically.",
    "If they respond favorably, we’ll launch the campaign.",
    "If the signal is weak, use airplane mode briefly.",
    "If the floor creaks, step on the side.",
    "If the answer is unclear, check the rubric again.",
    "If your suitcase is too full, remove the heavy items.",
    "If the notes are messy, rewrite them neatly.",
    "If we exceed the word limit, trim the conclusion.",
    "If the design is approved, we’ll start production.",
    "If she can’t make it, I’ll attend in her place.",
    "If you’re logged out, reauthenticate with your password.",
    "If the speaker goes over time, signal them subtly.",
    "If the lights dim, it might be a power dip.",
    "If there’s no parking, try the side lot.",
    "If the pet starts scratching, check for fleas.",
    "If the signal drops again, switch to cellular.",
    "If we catch the sunrise, take a picture.",
    "If the feedback is harsh, take it constructively.",
    "If the classroom is locked, wait by the main office.",
    "If the dishes pile up, run the dishwasher.",
    "If the vacuum clogs, check the hose for blockages.",
    "If the assignment confuses you, email the professor.",
    "If the code is commented well, it’s easier to read.",
    "If your eyes are dry, blink more often.",
    "If you hear a beep, check the smoke detector.",
    "If the ceiling leaks again, call the landlord.",
    "If the kids are quiet, they’re probably up to something.",
    "If she turns off her camera, don’t call on her.",
    "If the oven timer rings, pull out the tray.",
    "If you fold the paper, it fits in the envelope.",
    "If the milk smells sour, don’t drink it.",
    "If your leg cramps, stretch it gently.",
    "If the gate creaks, apply some oil.",
    "If this pen runs out, use the blue one instead.",
    "If your email bounces, check the address spelling.",
    "If you let the dough rest, it’ll rise properly.",
    "If the curtain is too long, hem it slightly.",
    "If the volume is low, turn up the dial.",
    "If the battery drains fast, close background apps.",
    "If the match ends in a tie, we’ll go to overtime.",
    "If the spice is too strong, add a dairy base.",
    "If your download is slow, pause other devices.",
    "If the garage is locked, use the side door.",
    "If the water pressure drops, check the main valve.",
    "If the fan rattles, clean the blades.",
    "If the blanket is thin, add another on top.",
    "If you can’t sleep, read a book.",
    "If you get an error message, take a screenshot.",
    "If your shirt wrinkles, iron it lightly.",
    "If the dough sticks, dust the surface with flour.",
    "If the socks don’t match, wear boots.",
    "If the seat is taken, ask for another row.",
    "If the forecast changes, adjust your outfit.",
    "If the windows fog up, use the defogger.",
    "If you have leftovers, label the container.",
    "If the plan works, use it again next time.",
    "If you press the red button, the alarm will sound.",
    "We will cancel the trip if the storm intensifies overnight.",
    "If she studies diligently, she will pass the final exam.",
    "The plants will wither if they are not watered regularly.",
    "If I see him at the conference, I will introduce myself.",
    "You will miss the train if you keep walking this slowly.",
    "If they agree to the terms, we can proceed with the merger.",
    "The car will not start if the battery is dead.",
    "If you heat the oven now, dinner will be ready sooner.",
    "Our team will win if we score another goal in the first half.",
    "If the flight is delayed, we will have to rebook the hotel.",
    "She will buy the tickets if they are still available tomorrow.",
    "If the meeting runs late, lunch will be postponed.",
    "He will attend the seminar if his schedule allows it.",
    "If you speak clearly, the audience will understand you.",
    "The document will print correctly if you choose the right settings.",
    "If the temperature rises, the ice will melt faster.",
    "You will receive a refund if the product is defective.",
    "If the phone rings, please answer it immediately.",
    "We will start the project if the funding is approved.",
    "If you follow the recipe, the cake will turn out perfectly.",
    "The cat will run away if the door is left open.",
    "If they call before noon, we can include them in the meeting.",
    "I will lend you the book if you promise to return it.",
    "If the train leaves on time, we will arrive by evening.",
    "He will go jogging if the weather clears up.",
    "If the class ends early, we can grab coffee afterwards.",
    "We will accept the offer if the price is reasonable.",
    "If she texts me, I will let you know immediately.",
    "The lights will stay on if the generator keeps running.",
    "If we take the earlier bus, we will reach before sunset.",
    "He will join us if he finishes work ahead of schedule.",
    "If the software updates, the bug might disappear.",
    "We will order dessert if everyone agrees.",
    "If the package arrives late, we will request a replacement.",
    "She will sign the contract if her lawyer approves it.",
    "If I have time later, I will clean the garage.",
    "We will postpone the trip if it rains tomorrow.",
    "If the museum is open, we should visit it.",
    "You will get sick if you don’t wear a coat in this weather.",
    "If the sale is still on, I’ll buy the jacket.",
    "They will start without us if we don’t hurry.",
    "If the queue moves quickly, we’ll be inside in no time.",
    "The party will be a success if everyone brings a dish.",
    "If the lights flicker, check the circuit breaker.",
    "We will upgrade the system if the budget allows.",
    "If the room feels stuffy, open the windows.",
    "The festival will be canceled if it rains all day.",
    "If you exercise regularly, you will feel more energetic.",
    "I will attend the wedding if I can get the day off.",
    "If the printer jams, turn it off and on again.",
    "We will add more seats if more people register.",
    "If the offer expires, we will look for alternatives.",
    "The store will restock the item if demand increases.",
    "If the school closes, classes will move online.",
    "He will apologize if he realizes his mistake.",
    "If the road is blocked, we will take the detour.",
    "The concert will start on time if everyone is seated.",
    "If the recipe fails, we will order takeout instead.",
    "I will buy more paint if we run out.",
    "If the sun sets, the streetlights will turn on.",
    "We will delay the announcement if more data is needed.",
    "If the rain stops, the children will play outside.",
    "She will attend the conference if her paper is accepted.",
    "If the phone battery dies, plug it into the charger.",
    "They will extend the deadline if the request is reasonable.",
    "If the door is locked, use the spare key.",
    "I will call you if I find anything important.",
    "If the price drops, we should buy it immediately.",
    "The flowers will bloom if you water them daily.",
    "If the heater breaks, call the repair service.",
    "We will leave earlier if traffic is heavy.",
    "If the river overflows, the lower fields will flood.",
    "She will join the club if her friend does too.",
    "If the match is postponed, tickets will still be valid.",
    "I will walk home if the bus doesn’t come soon.",
    "If the glass falls, it will shatter.",
    "We will return the item if it doesn’t fit.",
    "If the book is popular, they will print more copies.",
    "The computer will restart if the update finishes.",
    "If the movie is good, we’ll recommend it.",
    "I will turn on the heat if it gets too cold.",
    "If the chair breaks, replace it immediately.",
    "We will host the meeting if the venue is ready.",
    "If the plan works, we will celebrate.",
    "She will pass the course if she submits her assignments.",
    "If the bus arrives early, we can grab breakfast first.",
    "I will read the report if I have spare time.",
    "If the weather is nice, we will eat outside.",
    "We will repaint the room if the color fades.",
    "If the traffic clears, we will make it on time.",
    "He will drive us if his car is available.",
    "If the lock is broken, call maintenance.",
    "The crowd will cheer if the team scores.",
    "If the train stops, it might be a signal failure.",
    "I will write to you if I hear anything.",
    "If the exam is postponed, we will have more time to prepare.",
    "The shop will reopen if renovations finish early.",
    "If the soup is too salty, add more water.",
    "We will plant trees if the ground is soft enough.",
    "If the clock stops, replace the battery.",
    "I will finish the book if I can stay awake.",
    "If the teacher cancels class, we can go home.",
    "We will paint the fence if the weather stays dry.",
    "If the signal is weak, move closer to the router.",
    "The dog will bark if it hears footsteps outside.",
    "If the lightbulb burns out, change it.",
    "We will move the meeting if the room is unavailable.",
    "If the oven beeps, the cake is ready.",
    "I will join the game if there is space on the team.",
    "If the road is icy, drive carefully.",
    "We will win the bid if our price is lower.",
    "If the fridge is empty, go grocery shopping.",
    "The show will be canceled if the lead actor is ill.",
    "If the machine breaks, stop using it.",
    "We will celebrate if the results are good.",
    "If the website crashes, contact IT.",
    "I will wear the dress if it still fits.",
    "If the train is full, wait for the next one.",
    "The project will finish on time if everyone helps.",
    "If the bell rings, the lesson is over.",
    "We will bake cookies if we have enough sugar.",
    "If the day is clear, we will go hiking.",
    "She will take the job if the salary meets her needs.",
    "If the recipe works, we can share it.",
    "I will water the garden if the soil is dry.",
    "If the box is heavy, ask for help carrying it.",
    "We will repaint the wall if it gets stained.",
    "If the show sells out, we will buy resale tickets.",
    "The plan will succeed if everyone cooperates.",
    "If the price rises, fewer people will buy it.",
    "I will feed the cat if you are running late.",
    "If the car is repaired, we will drive to the beach.",
    "We will set up tents if we go camping.",
    "If the movie ends early, we can get ice cream.",
    "I will return the call if they leave a message.",
    "If the cake burns, we will bake another.",
    "We will book the flight if the price is right.",
    "If the game ends in a draw, there will be overtime.",
    "I will stay in if it starts to rain.",
    "If the library is closed, we can study at the café.",
    "We will take photos if the sunset is beautiful.",
    "If the crowd grows too large, close the gates.",
    "I will write the essay if I finish the reading.",
    "If the soup boils over, turn down the heat.",
    "We will light the fire if it gets chilly.",
    "If the milk expires, throw it away.",
    "I will attend the lecture if the topic interests me.",
    "If the boat is full, wait for the next ride.",
    "We will walk the dog if the weather is nice.",
    "If the report is ready, send it immediately.",
    "I will sweep the floor if it is dusty.",
    "If the shelves are empty, restock them.",
    "We will eat early if we get hungry.",
    "If the roof leaks, call a contractor.",
    "I will fix the faucet if it keeps dripping.",
    "If the bus is late, take a taxi.",
    "We will paint the mural if the wall is clean.",
    "If the message is urgent, reply immediately.",
    "I will visit you if I am in town.",
    "If the suitcase is too heavy, remove some items.",
    "We will build the fence if the materials arrive.",
    "If the keys are lost, get a spare made.",
    "I will cut the grass if it grows too long.",
    "If the shop is crowded, come back later.",
    "We will rehearse if the stage is free.",
    "If the machine overheats, turn it off.",
    "I will bring snacks if we watch a movie.",
    "If the glass is dirty, wash it.",
    "We will call the plumber if the sink is clogged.",
    "If the lake freezes, we can skate on it.",
    "I will visit the park if it is sunny.",
    "If the rent increases, we will move.",
    "We will start the barbecue if the grill is ready.",
    "If the computer is slow, restart it.",
    "I will feed the birds if they come to the yard.",
    "If the jacket is too small, return it.",
    "We will go skiing if there is enough snow.",
    "If the chair is wobbly, tighten the screws.",
    "I will send the package if I have time tomorrow.",
    "If the music is too loud, turn it down.",
    "We will lock the door if we leave the house.",
    "If the candle burns out, light another.",
    "I will walk with you if you want company.",
    "If the test is easy, we will finish quickly.",
    "We will try again if this plan fails.",
    "If the weather forecast changes, we will adjust plans.",
    "I will stay late if work isn’t finished.",
    "If the plane is delayed, call the hotel.",
    "We will order pizza if no one wants to cook.",
    "If the show starts late, we will miss the bus.",
    "I will bring dessert if you make dinner.",
    "If the printer is out of ink, replace the cartridge.",
    "We will save money if we cancel the subscription.",
    "If the line is too long, come back later.",
    "I will carry the bags if they are heavy.",
    "If the pool is open, we can swim.",
    "We will decorate the tree if we have ornaments.",
    "If the sky clears, we can see the stars.",
    "I will open the window if it gets hot.",
    "If the car is clean, it will sell faster.",
    "We will take turns driving if the trip is long.",
    "If the bread goes stale, make breadcrumbs.",
    "I will draw a map if you need directions.",
    "If the city approves, we will build a park.",
    "We will clap if the performance is good.",
    "If the soup is cold, reheat it.",
    "I will attend the party if I’m invited.",
    "If the plant dies, replace it.",
    "We will bake a cake if it’s your birthday.",
    "If the photo is blurry, take another.",
    "I will join the club if my friends do.",
    "If the doorbell rings, answer it quickly.",
]
# 667

subjunctive_templates = [
    "If I were a bird, I would fly across the ocean.",
    "If he had known about the meeting, he would have come earlier.",
    "If she were more confident, she might speak up in class.",
    "Had we seen the warning signs, we would have evacuated sooner.",
    "If they were interested, they would have called back by now.",
    "If I had taken that job offer, I'd be living in New York.",
    "If you were a little more patient, things might go smoother.",
    "If she had asked for help, we could have assisted her.",
    "If the weather had been better, we would have gone to the beach.",
    "Were I in your position, I'd do the same thing.",
    "If he were more careful, he wouldn't make so many mistakes.",
    "If she had studied harder, she might have passed the exam.",
    "If they had practiced more, they would've won the game.",
    "If we were closer, we would visit more often.",
    "Had he remembered her birthday, she wouldn't be upset.",
    "If I were rich, I'd donate to every charity I believe in.",
    "If she had driven slower, she might have avoided the accident.",
    "If you had told me sooner, I would've fixed it right away.",
    "If he had worn his raincoat, he wouldn't be soaked now.",
    "If I were still in high school, I'd join the drama club again.",
    "If the train had been on time, we wouldn't have missed the flight.",
    "If they had accepted the offer, the company would be thriving now.",
    "Were it not for the fog, we'd have landed on time.",
    "If you were less tired, you could join us tonight.",
    "If I had known the answer, I would have raised my hand.",
    "If the dog had stayed indoors, it wouldn't have gotten muddy.",
    "If we had packed the charger, we'd be able to work right now.",
    "If she had told the truth, they might have forgiven her.",
    "If I were invisible, I'd sneak into the concert.",
    "If they had paid attention, they would have caught the mistake.",
    "If he had followed the recipe, the cake would've turned out fine.",
    "If I had taken the earlier train, I wouldn't be late.",
    "If the teacher had explained better, I wouldn't be confused.",
    "If you had locked the door, the laptop wouldn't be missing.",
    "If we were in Paris, we'd visit the Eiffel Tower today.",
    "If she were my sister, I'd be proud of her.",
    "Had we brought umbrellas, we wouldn't be drenched.",
    "If they had checked the engine, the car wouldn't have stalled.",
    "If he were more organized, he'd find things faster.",
    "If she were still awake, she'd respond to your message.",
    "If I had remembered my lines, the play would've gone smoothly.",
    "If you had arrived earlier, you'd have seen the performance.",
    "If he had saved more money, he could have bought the house.",
    "If the wind were calmer, we'd take the boat out.",
    "If she had trained harder, she might have qualified for finals.",
    "If I had spoken up, things might have ended differently.",
    "If we were in charge, we'd handle things better.",
    "If he had left on time, he wouldn't be stuck in traffic.",
    "If she had answered the call, we'd know by now.",
    "If I had stayed in school, I might have finished the degree.",
    "If the bridge were still intact, we'd cross it safely.",
    "If he were the mayor, things would be different.",
    "Had she prepared a speech, she wouldn't be fumbling now.",
    "If you had watered the plants, they wouldn't be wilting.",
    "If I had noticed the sign, I wouldn't have parked here.",
    "If the alarm had gone off, we would have woken up.",
    "If they were paying attention, they'd see the obvious flaw.",
    "If I were braver, I'd confront him directly.",
    "If she had listened to her instincts, she'd be happier.",
    "If you had chosen the other route, we'd be there already.",
    "If the light hadn't turned red, we'd have made it through.",
    "If I had spoken slower, he might have understood me.",
    "If you were more empathetic, you'd see her side.",
    "If the team had trained more, they could have won gold.",
    "If I were taller, I'd try out for the basketball team.",
    "If the file had saved, we wouldn't have lost the work.",
    "If she had been more cautious, this wouldn't have happened.",
    "If he had called last night, we would have made a plan.",
    "If we were better prepared, we'd present with confidence.",
    "If I were in charge, I'd cancel the meeting.",
    "If the battery had lasted longer, we could've finished the movie.",
    "If they had taken the shortcut, they'd be here already.",
    "If you had reminded me, I wouldn't have forgotten.",
    "If the room were warmer, I'd stay a bit longer.",
    "If I were more spontaneous, I'd join you on that trip.",
    "If she had brought a jacket, she wouldn't be cold.",
    "If he had turned left, we'd be at the restaurant by now.",
    "If I had caught the error, we'd have avoided the issue.",
    "If the door hadn't jammed, we'd be inside already.",
    "If we had more experience, we might've gotten the job.",
    "If I had reviewed the notes, I'd do better on the test.",
    "If he had apologized earlier, she might have forgiven him.",
    "If you were more flexible, we could work this out.",
    "If the power hadn't gone out, dinner would be ready now.",
    "If she had remembered his name, it would've gone smoother.",
    "If we were less tired, we'd keep walking.",
    "If I had picked up the phone, I would've heard the news.",
    "If they had followed the signs, they wouldn't be lost.",
    "If the car had more gas, we could drive farther.",
    "If you had believed in yourself, you would have succeeded.",
    "If the laptop had been charged, we wouldn't need a plug.",
    "If I had closed the window, the papers wouldn't have flown away.",
    "If she had spoken up, things might have changed.",
    "If we were more organized, we wouldn't feel so rushed.",
    "If the roof were stronger, it would've held during the storm.",
    "If he had checked the time, he wouldn't have missed the call.",
    "If I were faster, I could have caught the train.",
    "If they were less distracted, they might have heard the announcement.",
    "If you had cleaned up, the mess wouldn't be this bad.",
    "If we had asked for directions, we'd be there by now.",
    "If she had worn boots, her feet wouldn't be soaked.",
    "If he were more optimistic, he'd see the good side.",
    "If I had trusted my gut, I might have avoided trouble.",
    "If the machine had worked, production wouldn't have stopped.",
    "If we were in agreement, we'd move forward together.",
    "If he had told the truth, the outcome might be different.",
    "If she were older, she could drive legally.",
    "If they had practiced more, the show would've gone better.",
    "If I had stayed longer, I would've seen it happen.",
    "If the software had updated, the bug might be gone.",
    "If you were more focused, you'd see the solution.",
    "If the bus hadn't broken down, we'd be home already.",
    "Had I worn gloves, my hands wouldn't be this cold.",
    "If she were more assertive, people wouldn't interrupt her.",
    "If we had double-checked the schedule, we'd have arrived on time.",
    "If he had followed the map, he'd be here already.",
    "If I were you, I'd take that opportunity.",
    "If they had read the instructions, nothing would have gone wrong.",
    "If she were less nervous, her speech would flow better.",
    "If I had waited five more minutes, I'd have seen him.",
    "If the stove were turned off, the soup wouldn't be boiling.",
    "If we had tested the system, it wouldn't have failed.",
    "If the instructions were clearer, this wouldn't be happening.",
    "Were he more open, people would relate to him better.",
    "If I had taken the call, I'd know the details.",
    "If the storm had lasted longer, we might be stranded.",
    "If she had backed up her files, she wouldn't have lost them.",
    "If he were less distracted, his work would improve.",
    "Had they brought food, we wouldn't be hungry now.",
    "If you were listening, you'd know what I said.",
    "If we had checked the weather, we'd have brought jackets.",
    "If she had gotten the promotion, she'd be celebrating.",
    "If he were in town, we'd meet up today.",
    "If I had asked earlier, I might've gotten a discount.",
    "If the lights were working, the hallway wouldn't be so dark.",
    "If the teacher had clarified, we'd understand the concept.",
    "If she were less hesitant, she'd take more chances.",
    "If I had gone to the event, I'd have met them.",
    "If we were better funded, the program would thrive.",
    "If he had followed protocol, there would've been no issue.",
    "If I were feeling better, I'd come with you.",
    "If the app hadn't crashed, I'd have placed the order.",
    "If you were more consistent, results would improve.",
    "If they had sent the email, we'd know what to do.",
    "If she had booked sooner, she'd have a better seat.",
    "If I had taken notes, I wouldn't be lost now.",
    "If we were allowed to, we'd join the committee.",
    "If the mail had arrived earlier, I'd have signed it today.",
    "If she were more decisive, the team would follow her lead.",
    "If I had done my research, I'd be prepared now.",
    "If he had known the deadline, he'd have submitted it.",
    "If they were friendlier, the event would be more enjoyable.",
    "If the ceiling weren't leaking, we'd sit in the living room.",
    "If I had reviewed the contract, I'd have caught that clause.",
    "If the charger had worked, we wouldn't be out of battery.",
    "If she had set a reminder, she wouldn't have forgotten.",
    "If we had stayed on the trail, we wouldn't be lost.",
    "If you were more confident, you'd ace the interview.",
    "If the plan had been tested, it wouldn't have failed.",
    "If I had been patient, things might have worked out.",
    "If they had fixed the bug, the system wouldn't crash.",
    "If she were available, she'd join the call.",
    "If we were aware of the risks, we'd act differently.",
    "If I were more motivated, I'd finish this project tonight.",
    "If the screen hadn't cracked, I wouldn't need a new phone.",
    "If you had taken the warning seriously, this wouldn't have happened.",
    "If I had backed up my files, I wouldn't be panicking.",
    "If she had brought her ID, she could have entered.",
    "If the flight had been delayed, I wouldn't have missed it.",
    "If we were better equipped, we'd complete the hike.",
    "If he had printed the tickets, we'd be inside already.",
    "If you had listened to me, we wouldn't be here.",
    "If the bridge weren't under repair, we'd use it.",
    "If she were more attentive, she'd notice the pattern.",
    "If we had secured the tent, it wouldn't have collapsed.",
    "If I had spoken earlier, my voice might've been heard.",
    "If they were informed, they wouldn't ask redundant questions.",
    "If the computer hadn't frozen, the file would be saved.",
    "If she were less distracted, she'd make fewer errors.",
    "If I had brought my wallet, I'd pay for lunch.",
    "If he were more generous, he'd have donated already.",
    "If they had scheduled better, no conflicts would arise.",
    "If you were more polite, people might respond better.",
    "If the painting hadn't fallen, the frame would still be intact.",
    "If we were more careful, we wouldn't have spilled anything.",
    "If I had spoken with her, I might understand the issue.",
    "If she were more adventurous, she'd travel more often.",
    "If he had planned ahead, none of this would be necessary.",
    "If they were closer, they'd visit more often.",
    "If the tires had been checked, the blowout wouldn't have occurred.",
    "If you had waited for me, we'd have gone together.",
    "If she had charged her phone, she could call a cab.",
    "The line wouldn't be this long if we had voted earlier.",
    "I'd introduce myself if I were more outgoing.",
    "If he were in better shape, he'd climb the hill easily.",
    "If the report had been finalized, we could submit it.",
    "If they had arrived on time, we'd already be eating.",
    "If the power were restored, we could continue working.",
    "If you were less afraid, you might try something new.",
    "If I had been stronger, I wouldn't have given up.",
    "If I were better at small talk, networking events wouldn't stress me out.",
    "If she had seen the warning, she might not have clicked the link.",
    "Had we left ten minutes earlier, we would have caught the ferry.",
    "If the cat were braver, it would explore outside.",
    "If he had double-checked the settings, the app wouldn’t have crashed.",
    "If they were more flexible, we could negotiate a better deal.",
    "Were the situation reversed, you would feel differently.",
    "If I had grown up near the ocean, I might have learned to surf.",
    "If you were in my shoes, you’d understand my hesitation.",
    "If the fire had spread further, the entire block might have burned.",
    "If she were more outspoken, she'd be leading the team.",
    "If he had taken the back road, he’d have avoided the accident.",
    "If I had known about the deadline, I wouldn't have waited.",
    "Had they read the instructions, this wouldn’t have gone wrong.",
    "If the machine were calibrated properly, the results would be more accurate.",
    "If you had listened to the briefing, none of this would be surprising.",
    "If it were still raining, the streets would be flooded by now.",
    "If we had packed lighter, the hike would’ve been easier.",
    "If I had finished school earlier, I’d be working by now.",
    "If she were less cautious, she might take that leap.",
    "If the contract had been reviewed carefully, we’d have noticed the error.",
    "If the garden had been watered, the plants wouldn't be wilting.",
    "If the system were less fragile, we'd have pushed the update.",
    "If he had followed the trail markers, he wouldn’t be lost now.",
    "If you had answered the phone, we’d have resolved this hours ago.",
    "If I were more optimistic, I’d say we still have a chance.",
    "If the email had gone through, they would have responded by now.",
    "If we had invested then, we’d be rich today.",
    "If you had spoken up earlier, we might have changed the plan.",
    "Were I not so tired, I’d stay for another round.",
    "If they had used stronger passwords, their accounts wouldn’t have been hacked.",
    "If he were truly sorry, he’d make an effort to apologize.",
    "If I had brought my tools, I could fix that right now.",
    "If she were around, she’d know what to do.",
    "Had we considered the consequences, we might have acted differently.",
    "If the weather were less humid, we could sit outside.",
    "If she had set her alarm, she wouldn't have missed the flight.",
    "If I were not so swamped with work, I’d visit more often.",
    "If the notes had been clearer, we’d all understand the topic.",
    "If you were more organized, these mistakes wouldn’t keep happening.",
    "If they had consulted legal, we wouldn’t be in this mess.",
    "If he had declined the offer, he’d have regretted it.",
    "If the light weren’t so dim, I’d keep reading.",
    "If she had asked first, I would have said yes.",
    "If the road hadn’t iced over, they’d have made it safely.",
    "If I had trained more, I might have qualified.",
    "If he were less distracted, he would have noticed the signal.",
    "If we had picked the alternate route, we'd be there already.",
    "If the stove were working, I’d cook something hot.",
    "If she were more patient, she'd have waited for the result.",
    "If he had apologized, things would be better now.",
    "If the data were more reliable, we could publish it.",
    "If we had tested the prototype, we’d have caught the flaw.",
    "If the lights had stayed on, we could have finished.",
    "If she had been warned, none of this would have happened.",
    "If the kids were quieter, I could focus.",
    "If I were more fluent, I’d write the essay in French.",
    "If the package had arrived on time, we wouldn’t be scrambling.",
    "If they had verified the address, the shipment wouldn’t be late.",
    "If I had taken a different path, who knows where I’d be now.",
    "If the judge were fair, the outcome would be different.",
    "If the microphone hadn’t failed, we’d have a recording.",
    "If she had responded sooner, we could’ve adjusted our schedule.",
    "If the engine had been checked, the trip wouldn’t be delayed.",
    "If I were less afraid of heights, I’d go skydiving.",
    "If you had told me then, I’d have done something.",
    "If he had listened to her, this wouldn’t have escalated.",
    "If I had booked earlier, I could’ve gotten a discount.",
    "If the system weren’t overloaded, the site would be responsive.",
    "If they were more creative, the proposal would be stronger.",
    "If we had stopped to refuel, we wouldn’t have stalled.",
    "If the dog had stayed in the yard, he wouldn’t be lost.",
    "If she had studied the map, she’d know the route.",
    "If you were less hasty, the results would improve.",
    "If the windows were open, there’d be a breeze.",
    "If I had worn my boots, my feet would be dry.",
    "If they had trusted their instincts, they might have avoided trouble.",
    "If she were less self-conscious, she'd speak more confidently.",
    "If he had stayed in school, he’d be graduating this year.",
    "If you had taken the last exit, we’d already be there.",
    "If the lights had worked, we wouldn’t have needed flashlights.",
    "If I had been braver, I would have told him the truth.",
    "If the water were warmer, I’d go for a swim.",
    "If they had read the terms, they might not have agreed.",
    "If he were more mindful, he’d remember your birthday.",
    "If I had gotten the job, I’d be moving next week.",
    "If the forecast had been right, we wouldn’t be soaked.",
    "If the door had latched, it wouldn’t have swung open.",
    "If I were more decisive, this would’ve been over already.",
    "If you had brought snacks, we wouldn't be starving.",
    "If the room were less crowded, I’d stay longer.",
    "If he were here now, he'd be laughing at us.",
    "If she had planned better, we’d have avoided the rush.",
    "If the park were open, we’d be walking there now.",
    "If I had caught the bus, I’d be downtown already.",
    "If you were less skeptical, you might believe him.",
    "If they had accepted the invitation, it’d be a full house.",
    "If the chair were sturdier, I’d sit without worry.",
    "If she had cooked the pasta longer, it wouldn’t be so tough.",
    "If the timeline were extended, we could polish the work.",
    "If I had taken a nap, I wouldn’t feel like a zombie.",
    "If he had rehearsed, his presentation would’ve gone smoother.",
    "If the speaker had stayed on topic, the talk would be useful.",
    "If you were more flexible, we could find a compromise.",
    "If she were available, I’d schedule a meeting now.",
    "If we had hired more staff, the launch would’ve gone better.",
    "If I had remembered my ID, I wouldn’t be stuck outside.",
    "If he had saved his work, the file wouldn’t be lost.",
    "If the door were painted, it would match the trim.",
    "If I had practiced, I’d feel more confident now.",
    "If the cat hadn’t escaped, we’d be leaving already.",
    "If she had asked for help, I would’ve stepped in.",
    "If I were in charge, we’d change the entire process.",
    "If the weather had held up, the ceremony would be outside.",
    "If he had read the prompt, the essay would make sense.",
    "If the cord were longer, it would reach the outlet.",
    "If I were more technically skilled, I’d repair it myself.",
    "If you had cleaned the lens, the photo would be clearer.",
    "If they had warned us, we would have brought supplies.",
    "If the meeting had ended earlier, I could’ve joined the call.",
    "If the water weren’t so choppy, we could kayak today.",
    "If he had spoken up, his concerns might be addressed.",
    "If I had gone to the doctor, I’d feel better by now.",
    "If the app were compatible, it would run on your phone.",
    "If we had caught the earlier bus, we’d be downtown already.",
    "If the printer were working, I’d hand you the form.",
    "If he had paid attention, he’d know what’s happening.",
    "If she were less anxious, she’d enjoy it more.",
    "If the stove had been turned off, the soup wouldn’t have burned.",
    "If I had changed the batteries, the remote would work.",
    "If the light had been on, we wouldn’t have tripped.",
    "If they had followed the instructions, it would be assembled.",
    "If the house weren’t so far, we’d visit more often.",
    "If he had closed the deal, we’d be celebrating now.",
    "If I were better rested, I wouldn’t need this much coffee.",
    "If the baby were asleep, we could talk freely.",
    "If we had brought jackets, we wouldn’t be freezing.",
    "If the lock had been changed, the key wouldn’t work.",
    "If you were less stubborn, we might get along better.",
    "If the server had saved the draft, I wouldn't have to start over.",
    "If the battery weren’t so old, it would hold a charge.",
    "If I were born in another country, my life would be different.",
    "If she had known her strength, she wouldn’t have doubted herself.",
    "If they had taken notes, studying would be easier.",
    "If the package were insured, we'd get a refund.",
    "If he were better prepared, he’d nail the interview.",
    "If I had driven, we wouldn’t have been late.",
    "If we had switched seats, you’d have seen the screen better.",
    "If the signal had been clearer, we’d have understood the call.",
    "If I were able to sing, I’d join the choir.",
    "If she were less distracted, she’d have caught the typo.",
    "If you had labeled the boxes, unpacking would be easier.",
    "If the forecast were accurate, we’d be sunbathing.",
    "If he had parked closer, we wouldn’t be walking this far.",
    "If she had trusted her team, the plan would’ve worked.",
    "If they had planned ahead, this chaos wouldn’t exist.",
    "If I had heard the knock, I would’ve answered.",
    "If the app were faster, I’d use it regularly.",
    "If the backup had worked, we wouldn’t have lost data.",
    "If the curtains were drawn, the sun wouldn’t glare.",
    "If the payment had processed, we’d be done here.",
    "If I had turned left, we wouldn’t be stuck in traffic.",
    "If she had joined the club, she’d have made new friends.",
    "If the hammer were nearby, I’d hang the painting.",
    "If they had checked the time zone, the meeting would’ve synced.",
    "If he were here, we’d have already started.",
    "If the sound weren’t muted, we’d hear the alert.",
    "If we had signed earlier, we’d be locked into a better rate.",
    "If she had taken her meds, she’d be feeling better.",
    "If the screen weren’t cracked, I’d keep the phone.",
    "If you were paying attention, you’d catch the cue.",
    "If they were closer, they’d be here by now.",
    "If I had eaten breakfast, I wouldn’t feel faint.",
    "If the textbook were open, I’d point to the page.",
    "If we had budgeted more, we could afford new chairs.",
    "If he had asked permission, this wouldn’t be an issue.",
    "If the soap hadn’t spilled, the floor wouldn’t be slippery.",
    "If she were a bit bolder, she'd ask him out.",
    "If I had checked the weather, I’d have packed an umbrella.",
    "If the schedule were less rigid, we could add another activity.",
    "If we had caught the signal, we could triangulate their location.",
    "If the tires had been rotated, the ride would be smoother.",
    "If you had taken notes, reviewing would be easier.",
    "If the teacher were more engaging, I’d enjoy the class.",
    "If the flight had landed on time, I’d be there already.",
    "If they had played defense better, they might’ve won.",
    "If I were less tired, I’d keep working.",
    "If we had anticipated the problem, we could’ve avoided it.",
    "If she had adjusted the settings, the sound would be clearer.",
    "If the waiter had heard correctly, my order wouldn’t be wrong.",
    "If the table were level, the cups wouldn’t slide.",
    "If he had booked the room, we’d be checked in.",
    "If the list had included her name, she would’ve joined.",
    "If she were more organized, deadlines wouldn’t sneak up.",
    "If I had spoken slower, he might have understood.",
    "If the dog weren’t barking, I could hear you.",
    "If I were a better cook, I’d make dinner more often.",
    "If he had stretched first, he wouldn’t be sore.",
    "If the link had worked, I’d have signed up already.",
    "If the lighting were better, this photo would shine.",
    "If the guards were alert, no one would have gotten in.",
    "If I had taken the time, I’d have written a proper reply.",
    "If she had waited five minutes, we’d have arrived together.",
    "If we had stopped at the last exit, we could’ve eaten.",
    "If I had remembered your name, I’d have introduced you.",
    "If they had budgeted properly, they wouldn’t be overdrawn.",
    "If I had not hesitated, I might have won.",
    "If he were not so hesitant, he'd have said yes.",
    "If the situation were less tense, I'd say something.",
    "If she had listened to her gut, she wouldn’t regret it.",
    "If we had called ahead, there’d be a table for us.",
    "If you had reminded me, I wouldn’t have forgotten.",
    "If she had turned the knob slowly, the door wouldn’t creak.",
    "If I had checked the facts, I wouldn’t be wrong now.",
    "If he had rehearsed more, he'd be more confident.",
    "If she were here, she’d have handled this better.",
    "If I had taken that detour, I'd be home already.",
    "If the light weren’t so harsh, I’d stay longer.",
    "If you had stopped talking, I could have finished.",
    "If the cords were untangled, this would go faster.",
    "If I had reviewed the slides, I’d ace this talk.",
    "If you were more patient, we'd get through this smoothly.",
    "If he had secured the gate, the dog wouldn’t have escaped.",
    "If they were in sync, the project would flow better.",
    "If the story were shorter, I might read it now.",
    "If I had stayed focused, I'd be done already.",
    "If the app weren’t glitching, I could use it.",
    "If she had updated the file, the changes would show.",
    "If the package weren’t sealed, I’d inspect it.",
    "If he had backed up, there’d be no loss.",
    "If I had double-checked the address, we wouldn’t be lost.",
    "If I were taller, I would try out for the basketball team.",
    "We could have gone to the beach if the weather had been nicer.",
    "If she had studied harder, she might have passed the exam.",
    "If they had told me earlier, I could have helped.",
    "She might be happier if she were living closer to her family.",
    "If he had been more careful, the vase would not have broken.",
    "They would have finished on time if they had started earlier.",
    "If I were you, I would reconsider that decision.",
    "He would be more confident if he practiced more often.",
    "If I had known about the sale, I would have bought the jacket.",
    "We might have won if we had played better defense.",
    "If the roads were safer, more people would cycle to work.",
    "I could have attended if I had received an invitation.",
    "If she were more organized, she would get more done.",
    "They would have joined us if they had found a babysitter.",
    "If it had rained less, the festival could have continued.",
    "I might speak more fluently if I practiced daily.",
    "If you had explained it better, they might have understood.",
    "We would be healthier if we ate less sugar.",
    "If they had arrived earlier, we could have had dinner together.",
    "She might have avoided injury if she had been more cautious.",
    "If he were more patient, he would make fewer mistakes.",
    "We would have visited if we had had the time.",
    "If the train had come on time, we would not have been late.",
    "I might be less tired if I went to bed earlier.",
    "If the city were cleaner, it would attract more tourists.",
    "We could have met if our schedules had aligned.",
    "If the lights had worked, the event would have been better.",
    "She would be more relaxed if she took regular breaks.",
    "If I had been there, I might have stopped the argument.",
    "They might be less busy if they delegated tasks.",
    "If the bridge had been stronger, it would not have collapsed.",
    "I would take the risk if I were in your position.",
    "If she had spoken up, things might have gone differently.",
    "We could have stayed longer if the hotel had been cheaper.",
    "If it were not raining, we would go for a walk.",
    "He would have accepted if the offer had been higher.",
    "If I had driven slower, I would have avoided the ticket.",
    "We might be less stressed if we had more support.",
    "If the rules were clearer, fewer mistakes would be made.",
    "I would have joined the class if it had fit my schedule.",
    "If they had prepared better, they could have won the match.",
    "She might succeed if she were more persistent.",
    "If you had asked, I would have helped you.",
    "We would have enjoyed it more if the seats had been comfortable.",
    "If he were more focused, he would finish his work faster.",
    "I might have understood if the instructions had been simpler.",
    "If they had hired more staff, service would have improved.",
    "We could be saving money if we cooked at home.",
    "If she had been careful, she would not have lost her phone.",
    "I would have agreed if the terms had been fair.",
    "If the house were bigger, we could host more guests.",
    "We might have avoided the delay if we had left earlier.",
    "If I had prepared better, I would have done well.",
    "They would have stayed longer if they had felt welcome.",
    "If it were less expensive, more people would buy it.",
    "I could have learned faster if I had had a tutor.",
    "If she had listened, the problem might have been solved.",
    "We might be more productive if we took fewer breaks.",
    "If the park were closer, I would visit more often.",
    "I would have taken the job if it had been offered.",
    "If they had trained harder, they could have won gold.",
    "She might be more confident if she spoke more in class.",
    "If you had given me more notice, I could have prepared.",
    "We could have gone skiing if there had been more snow.",
    "If the meeting had ended sooner, we would have caught the train.",
    "He would do better if he were less distracted.",
    "If the instructions were clearer, I would follow them.",
    "We might have avoided confusion if we had planned better.",
    "If the weather had improved, the picnic could have happened.",
    "I would have joined if I had felt ready.",
    "If they were more careful, accidents would be less frequent.",
    "We could have saved money if we had compared prices.",
    "If you had stayed longer, we could have talked more.",
    "I might have succeeded if I had tried again.",
    "If the streets were safer, children could play outside.",
    "We would have left earlier if we had known about the traffic.",
    "If she had prepared more, she would not have been nervous.",
    "I would visit more if I had a car.",
    "If they had been more supportive, she might have stayed.",
    "We could have avoided this if we had been careful.",
    "If the test were shorter, students would feel less pressure.",
    "I might have enjoyed it if the food had been better.",
    "If he had listened, the issue could have been avoided.",
    "We would be less rushed if we left earlier.",
    "If they had been on time, we could have started sooner.",
    "I could have learned more if I had taken notes.",
    "If the internet were faster, work would be easier.",
    "We might have avoided the mistake if we had reviewed carefully.",
    "If you had reminded me, I would have brought the keys.",
    "I would go out more if I lived in the city.",
    "If the store had been open, we would have bought it.",
    "We could have finished earlier if we had been more focused.",
    "If she were stronger, she could lift it herself.",
    "I might have joined the team if I had more free time.",
    "If he had apologized, they might have forgiven him.",
    "We would not be here if the map had been accurate.",
    "If it were warmer, we could eat outside.",
    "I would have passed if I had studied more.",
    "If they had called sooner, we could have helped.",
    "We might be ahead if we had made better choices.",
    "If the light had been green, we would have gone.",
    "I could have attended if my schedule had been free.",
    "If she were more patient, her work would improve.",
    "We would have been early if the bus had arrived.",
    "If you had told me, I might have acted differently.",
    "I might be less nervous if I prepared more.",
    "If the tickets were cheaper, more people would attend.",
    "We could have fixed it if we had tried sooner.",
    "If he had driven slower, the accident might have been avoided.",
    "I would live abroad if I had the chance.",
    "If they had given us more time, we could have done better.",
    "We might have finished earlier if we had worked faster.",
    "If it were not so cold, we would walk instead.",
    "I would have bought it if it had been on sale.",
    "If the plane had not been delayed, we would be home.",
    "We could have avoided this problem if we had planned better.",
    "If she were friendlier, she might make more friends.",
    "I might have tried again if I had felt confident.",
    "If they had prepared earlier, it would have gone smoothly.",
    "We would be ahead if we had left earlier.",
    "If the road were wider, traffic would move faster.",
    "I would have joined if I had been invited.",
    "If it had been sunny, we would have gone outside.",
    "We might have caught the bus if we had run.",
    "If he were taller, he could reach the top shelf.",
    "I could have done better if I had practiced more.",
    "If the shop had stayed open, we could have bought it.",
    "We would have succeeded if we had been ready.",
    "If she had spoken louder, everyone could have heard.",
    "I might have visited if I had been in town.",
    "If the signal had been stronger, the call would not have dropped.",
    "We could have avoided the delay if we had known.",
    "If it were less crowded, I would go more often.",
    "I would have acted differently if I had known the truth.",
    "If they had supported me, I might have stayed.",
    "We could have finished sooner if we had started earlier.",
    "If he had worked harder, he might have been promoted.",
    "I might have stayed if I had felt comfortable.",
    "If it were quieter, I could focus better.",
    "We would be further along if we had more resources.",
    "If she had smiled, he might have approached her.",
    "I could have avoided that if I had thought ahead.",
    "If they had been on time, we would not have waited.",
    "We might have made it if the train had been faster.",
    "If the food had been better, I would have eaten more.",
    "I would have joined if I had known about it.",
    "If the problem were simpler, I could solve it.",
    "We could have prevented this if we had acted sooner.",
    "If he had spoken honestly, trust could have been maintained.",
    "I might have helped if I had understood the situation.",
    "If they were more polite, people would like them more.",
    "We would be ready if we had packed last night.",
    "If the store had stocked it, we would have bought one.",
    "I could have learned faster if I had paid attention.",
    "If the event had been closer, more would have attended.",
    "We might have enjoyed it if we had been better prepared.",
    "If she had been on time, we could have started earlier.",
    "I would stay longer if I did not have to leave early.",
    "If the train had arrived, we would have boarded.",
    "We could have avoided the fight if we had listened.",
    "If it were brighter, I could read without a lamp.",
    "I might have finished sooner if I had worked steadily.",
    "If they had been kinder, the outcome might have changed.",
    "We would have caught the flight if we had left sooner.",
]
# 596